### ISSUE TITLE
Could I use the Babel plugin with any React Native styles?

### ISSUE THREAD

**Issue by nandorojo** [z0al/react-native-styled.macro#19]
Hey there, cool package. I came across it on Twitter the other day (I maintain [Dripsy](https://github.com/nandorojo/dripsy), a responsive design system for RNW.)

I think the static extraction of styles is a really cool idea that you have here. I'm wondering if there's a way I might be able to repurpose the Babel plugin for Dripsy to improve performance, namely on web. 

Would you have any suggestions for how I might do that? I don't really know my way around Babel, but I was wondering if your plugin could be generalized to any react native inline styles by chance.

Thanks so much!

**Comment by z0al** [comment]
:wave: @nandorojo 

> I'm wondering if there's a way I might be able to repurpose the Babel plugin for Dripsy

I'm afraid no. I didn't think of that when building the Babel Macro so what I have here is built specifically for this package.

> I don't really know my way around Babel

I'm on the same boat here :) . This is my first attempt and I barely got it to work. The code could use a lot of refactoring.

> Would you have any suggestions for how I might do that? 

AFAIK, the rule (limitation) here is simple: The styles declarations must never change at runtime.

This library was built with that in mind so I made a clear separation between: (1) the styles declarations and (2) when they should be applied. Let's take an example:

```javascript
styled(['bg-white', 'dark:bg-black'], {...variants})
```
I imagine it will be tempting for some users to create a wrapper hook like this:

```javascript
function useStyled(){
    const win = useWindowVariant()
    const dark = useColorScheme()
     // ... 
    return (styles: string[]) => {
        return styled(styles, {...win, ...dark});
    }
}

// component code
const styled = useStyled()
styled([...])
```

Sadly, in that case, the library will simply throw an [ error:](https://github.com/z0al/react-native-styled.macro/blob/5e0e69245c9d9c0fb2dc5dce09c65ac03f77c764/src/macro.ts#L101-L103) 

```
expected styled to be called with a list of string literals
```

They will also get the same error if the styles are not *strictly* string literals (e.g no variables, Template Literals ..etc) because it's hard to determine the actual style name at compile time.

To work around the situation above. Users would need to do something like this instead

```javascript
function useAllVariants(){
    const win = useWindowVariant()
    const dark = useColorScheme()
    return {..win, ...dark}
}

// Component code
const variants = useAllVariants()
styled([...], variants)
```

To support custom themes (not yet implemented) the users would create a `styled.config.js` which the library can statically import and determine the theme values.

I took a quick look at `Dripsy` and I see the `theme` is passed as an attribute to `DripsyProvider` which means you need to traverse the whole code to determine the theme value (if possible) during compilation.

To apply static optimizations to `Dripsy` I think you need to rethink the dynamic (non-deterministic) parts in the framework and try to minimize them as much as possible. Only then it will be easy to create a Babel plugin/macro for `Dripsy`.

Regardless of the approach you take. I doubt the macro in this library will be of any value.

**Comment by nandorojo** [comment]
Got it, I really appreciate the thorough explanation, very helpful. I'll have to give that some thought.

In your experience, do you find a significant performance difference by using build time styles?

**Comment by z0al** [comment]
> In your experience, do you find a significant performance difference by using build time styles?

Not sure, I didn't test that personally. But in general, I think there are two benefits to this approach:
 
(1) Less footprint (You don't include what you don't use. More interesting for Expo web) and
(2) *Potential* performance gain since it's easy to use `StyledSheet.create` for all styles.

> Exercise caution as abusing this can tax you in terms of optimizations. IDs enable optimizations through the bridge and memory in general. Referring to style objects directly will deprive you of these optimizations. 
> From: https://reactnative.dev/docs/stylesheet

**Comment by nandorojo** [comment]
That might be the case for style sheet on web (I believe it is.) But looking at RN's code, it looks like nothing but a plain object, unless I'm missing something (see the bottom): https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheet.js

**Comment by z0al** [comment]
I remember reading `Not implemented yet` on the website but I couldn't find it anymore. It might have not been implemented yet or ... a [myth](https://stackoverflow.com/a/56219676) :)

**Comment by z0al** [comment]
If it's not implemented yet then I doubt they will be any performance difference.

**Comment by nandorojo** [comment]
Haha yeah, I think `StyleSheet.create` is the myth of React Native. However, it does seem to cache styles on web.

**Comment by z0al** [comment]
Yep, It's implemented in RNW. But [not in RN](https://github.com/facebook/react-native/blob/00456211e591930f28a08356141fc8bec52fe3e5/Libraries/StyleSheet/StyleSheet.js#L218-L223). Maybe one day :)

I'm closing this for now as there is nothing actionable here. Please feel free to ping me again if there is something I can help you with. Good luck
