### ISSUE TITLE
Dynamic style inside styled

### ISSUE THREAD

**Issue by vikrantnegi** [z0al/react-native-styled.macro#23]
Hi, 
I just started using this library in my side project and I came across a situation where I need inject dynamic style inside the `...styled([])`. 

I want to change the `fontSize` to be different according to the prop passed. For eg.

```
  const fontSize = big ? 'text-6xl' : 'text-3xl';
```
and than use 
```
  <Text {...styled([fontSize, 'text-center', 'uppercase'])}>Text</Text>
```

 But It seems I cannot use a variable inside the styled. 
Is there anyway I can achieve the above or I am missing something here?

**Comment by z0al** [comment]
Hey @vikrantnegi . Thanks for trying this out :sparkles: 

You are indeed right. Style declarations should be static because the babel macro will use the values to inject styles at compile time.

For your case (which I think is fairly common) you need to utilize the variants param. like this:

```javascript
const CustomText = ({big)=> {
    return  <Text {...styled(['text-3xl', 'text-center', 'uppercase', 'big:text-6xl'], {big})}>Text</Text>
}
```

You would do the same if you want to implement e.g. a button with different styles:

```javascript

const MyButton = ({primary, warning, ...rest}) => {
    return <Button {...styled([/* you default styles*/, 'primary:text-blue-900', 'warning:text-orange-900'], {primary, warning)}/>
}
```

You can literally pass any key as a variant. The library will apply that style if the value is [Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

Does that make sense?

**Comment by vikrantnegi** [comment]
@z0al Thank you for quick reply. That does make sense.
