### ISSUE TITLE
Missing line-height (leading) styles

### ISSUE THREAD

**Issue by branislaav** [z0al/react-native-styled.macro#66]
Hi, I noticed that there are missing line-height (leading) styles is it on purpose or it was only forgotten?

**Comment by z0al** [comment]
It does actually support line-height but with the `line-h` instead of `leading`. 

Interestingly, I couldn't find it in the [style docs](https://github.com/z0al/react-native-styled.macro/blob/master/docs/styles.md) because I forgot to include it in the [generator script](https://github.com/z0al/react-native-styled.macro/blob/30aed69c340a3ee0a07afb6efbe1e5379344ac21/scripts/docs-gen.ts#L13) :facepalm: 

P.S I don't strictly follow TW naming btw. Regardless I don't mind naming this one to `leading` if people think it makes more sense.

**Comment by z0al** [comment]
[Here you go ](https://github.com/z0al/react-native-styled.macro/blob/master/docs/styles.md#line-height)

If you have suggestions or comments I'd love to hear them as part of https://github.com/z0al/react-native-styled.macro/issues/55. Thanks

**Comment by branislaav** [comment]
Thank you, I personally think `line-h` is better than `leading` but I was just expecting `leading` because of tailwind and didn't find line height in docs that's all. Also thank you for this library, I've used [tailwind-rn](https://github.com/vadimdemedes/tailwind-rn) on one project in work but this library seems much better :).

**Comment by z0al** [comment]
Glad you find it useful, thanks.
